INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR app.py:1891 Exception on /api/index [GET]
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 539, in connect
    sock = self._connect()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 596, in _connect
    raise err
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 584, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_session\sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 1540, in setex
    return self.execute_command('SETEX', name, time, value)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 1073, in get_connection
    connection.connect()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 192.168.33.128:6379. 由于目标计算机积极拒绝，无法连接。.
ERROR app.py:1975 Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 539, in connect
    sock = self._connect()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 596, in _connect
    raise err
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 584, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_session\sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 1540, in setex
    return self.execute_command('SETEX', name, time, value)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 1073, in get_connection
    connection.connect()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 192.168.33.128:6379. 由于目标计算机积极拒绝，无法连接。.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 539, in connect
    sock = self._connect()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 596, in _connect
    raise err
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 584, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_session\sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 1540, in setex
    return self.execute_command('SETEX', name, time, value)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 1073, in get_connection
    connection.connect()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 192.168.33.128:6379. 由于目标计算机积极拒绝，无法连接。.
INFO _internal.py:122 127.0.0.1 - - [07/Dec/2019 20:32:44] "GET /api/index HTTP/1.1" 500 -
ERROR app.py:1891 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 539, in connect
    sock = self._connect()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 596, in _connect
    raise err
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 584, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_session\sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 1540, in setex
    return self.execute_command('SETEX', name, time, value)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 1073, in get_connection
    connection.connect()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 192.168.33.128:6379. 由于目标计算机积极拒绝，无法连接。.
ERROR app.py:1975 Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 539, in connect
    sock = self._connect()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 596, in _connect
    raise err
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 584, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_session\sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 1540, in setex
    return self.execute_command('SETEX', name, time, value)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 1073, in get_connection
    connection.connect()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 192.168.33.128:6379. 由于目标计算机积极拒绝，无法连接。.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 539, in connect
    sock = self._connect()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 596, in _connect
    raise err
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 584, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_session\sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 1540, in setex
    return self.execute_command('SETEX', name, time, value)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 1073, in get_connection
    connection.connect()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 192.168.33.128:6379. 由于目标计算机积极拒绝，无法连接。.
INFO _internal.py:122 127.0.0.1 - - [07/Dec/2019 20:32:46] "GET /favicon.ico HTTP/1.1" 500 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR app.py:1891 Exception on /api/index [GET]
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_session\sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 1540, in setex
    return self.execute_command('SETEX', name, time, value)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 839, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 853, in parse_response
    response = connection.read_response()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 718, in read_response
    raise response
redis.exceptions.ResponseError: DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
ERROR app.py:1975 Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_session\sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 1540, in setex
    return self.execute_command('SETEX', name, time, value)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 839, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 853, in parse_response
    response = connection.read_response()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 718, in read_response
    raise response
redis.exceptions.ResponseError: DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_session\sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 1540, in setex
    return self.execute_command('SETEX', name, time, value)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 839, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 853, in parse_response
    response = connection.read_response()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 718, in read_response
    raise response
redis.exceptions.ResponseError: DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
INFO _internal.py:122 127.0.0.1 - - [07/Dec/2019 20:41:43] "GET /api/index HTTP/1.1" 500 -
ERROR app.py:1891 Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_session\sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 1540, in setex
    return self.execute_command('SETEX', name, time, value)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 839, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 853, in parse_response
    response = connection.read_response()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 718, in read_response
    raise response
redis.exceptions.ResponseError: DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
ERROR app.py:1975 Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_session\sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 1540, in setex
    return self.execute_command('SETEX', name, time, value)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 839, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 853, in parse_response
    response = connection.read_response()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 718, in read_response
    raise response
redis.exceptions.ResponseError: DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1969, in finalize_request
    response = self.process_response(response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2268, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_session\sessions.py", line 166, in save_session
    time=total_seconds(app.permanent_session_lifetime))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 1540, in setex
    return self.execute_command('SETEX', name, time, value)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 839, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\client.py", line 853, in parse_response
    response = connection.read_response()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\redis\connection.py", line 718, in read_response
    raise response
redis.exceptions.ResponseError: DENIED Redis is running in protected mode because protected mode is enabled, no bind address was specified, no authentication password is requested to clients. In this mode connections are only accepted from the loopback interface. If you want to connect from external computers to Redis you may adopt one of the following solutions: 1) Just disable protected mode sending the command 'CONFIG SET protected-mode no' from the loopback interface by connecting to Redis from the same host the server is running, however MAKE SURE Redis is not publicly accessible from internet if you do so. Use CONFIG REWRITE to make this change permanent. 2) Alternatively you can just disable the protected mode by editing the Redis configuration file, and setting the protected mode option to 'no', and then restarting the server. 3) If you started the server manually just for testing, restart it with the '--protected-mode no' option. 4) Setup a bind address or an authentication password. NOTE: You only need to do one of the above things in order for the server to start accepting connections from the outside.
INFO _internal.py:122 127.0.0.1 - - [07/Dec/2019 20:41:43] "GET /favicon.ico HTTP/1.1" 500 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [07/Dec/2019 21:53:24] "GET /api/index HTTP/1.1" 404 -
INFO _internal.py:122 127.0.0.1 - - [07/Dec/2019 21:53:25] "GET /favicon.ico HTTP/1.1" 404 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [07/Dec/2019 22:01:53] "GET /api/index HTTP/1.1" 200 -
ERROR __init__.py:97 Error: Directory migrations already exists and is not empty
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 13:39:04] "POST /api/register HTTP/1.1" 200 -
ERROR user_api.py:79 (pymysql.err.IntegrityError) (1062, "Duplicate entry 'admin@haizol.com' for key 'email'")
[SQL: INSERT INTO tb_user (create_time, update_time, is_del, name, email, password_hash) VALUES (%(create_time)s, %(update_time)s, %(is_del)s, %(name)s, %(email)s, %(password_hash)s)]
[parameters: {'create_time': datetime.datetime(2019, 12, 8, 13, 42, 49, 871622), 'update_time': datetime.datetime(2019, 12, 8, 13, 42, 49, 871622), 'is_del': '0', 'name': 'admin', 'email': 'admin@haizol.com', 'password_hash': 'pbkdf2:sha256:150000$2XrIAkGg$827441ca617f3d921077b5510e6e49d76e2eb83296ffa86032d07b9283dbbbc7'}]
(Background on this error at: http://sqlalche.me/e/gkpj)
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 13:42:49] "POST /api/register HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 13:43:10] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 13:43:16] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 13:56:03] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 13:59:34] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 16:25:46] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 16:29:15] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 16:36:31] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 17:37:28] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 17:37:28] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 17:40:08] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 17:40:08] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 17:40:30] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 17:40:31] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 17:43:59] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 17:43:59] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 17:45:27] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 17:45:27] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 17:47:07] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 17:47:07] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 17:48:06] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 17:48:06] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 19:26:13] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 19:26:13] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 19:31:28] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 19:31:28] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 19:32:48] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 19:32:48] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 19:33:09] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 19:33:10] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 19:33:17] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 19:33:17] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 19:33:24] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 19:33:25] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 19:37:11] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 19:37:11] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 19:46:18] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 19:46:18] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:07:58] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:07:58] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:11:42] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:23:08] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:23:09] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:24:16] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:27:22] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:27:22] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:27:46] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:27:46] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:29:26] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:29:26] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:29:56] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:30:22] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:30:50] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:30:50] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:30:53] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:01] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:01] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:04] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:07] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:07] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:07] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:08] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:10] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:11] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:11] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:11] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:11] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:23] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:24] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:24] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:24] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:37] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:40] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:31:54] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:32:01] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:33:01] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:33:01] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:33:21] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:33:21] "GET /favicon.ico HTTP/1.1" 404 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:33:40] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:33:43] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:33:43] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:33:43] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:33:48] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:33:48] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:33:48] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:33:48] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:33:56] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:34:00] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:34:10] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:34:10] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [08/Dec/2019 20:34:19] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [09/Dec/2019 23:12:25] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [09/Dec/2019 23:12:26] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [09/Dec/2019 23:17:24] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [09/Dec/2019 23:17:24] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [09/Dec/2019 23:17:28] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [09/Dec/2019 23:18:33] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [09/Dec/2019 23:21:01] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [09/Dec/2019 23:29:13] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [09/Dec/2019 23:29:13] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [09/Dec/2019 23:29:15] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [09/Dec/2019 23:29:38] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [09/Dec/2019 23:30:46] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [09/Dec/2019 23:30:46] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [09/Dec/2019 23:31:07] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [09/Dec/2019 23:31:08] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [09/Dec/2019 23:31:08] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [09/Dec/2019 23:31:24] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 22:23:17] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 22:23:37] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 22:23:37] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 22:23:37] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 22:25:29] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 22:30:01] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 22:31:21] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 22:39:16] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 22:39:16] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 22:39:19] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 22:39:55] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 22:48:22] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:02:38] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:02:58] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:02:59] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:11:25] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:11:25] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:11:48] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:11:48] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:12:13] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:12:13] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:12:13] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:12:19] "GET /api/logout HTTP/1.1" 404 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:12:48] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:12:50] "GET /api/logout HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:16:34] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:17:08] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:17:09] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:17:09] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:17:14] "GET /api/logout HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:17:53] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:17:56] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:18:05] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:18:09] "GET /api/logout HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:20:05] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:20:22] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:20:22] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:20:22] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:20:28] "GET /api/logout HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [10/Dec/2019 23:20:51] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:03:29] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:03:29] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:03:29] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:07:33] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:07:43] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:09:39] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:09:44] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:14:41] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:14:46] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:17:15] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:17:18] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:17:22] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:17:25] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:17:28] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:17:30] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:23:43] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:23:59] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:24:36] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:24:44] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:24:49] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:24:51] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:29:56] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:29:56] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:30:01] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:30:38] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:36:29] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:36:35] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:36:43] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:36:50] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:38:05] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:41:42] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:41:48] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:45:55] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:45:57] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:48:00] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:50:54] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 22:50:57] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [11/Dec/2019 23:02:15] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 21:48:32] "GET /api/case_list?query=&pagenum=1&pagesize=15 HTTP/1.1" 404 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 21:48:32] "GET /api/case_list?query=&pagenum=1&pagesize=15 HTTP/1.1" 404 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 21:48:39] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 21:48:39] "GET /api/case_list?query=&pagenum=1&pagesize=15 HTTP/1.1" 404 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 21:48:51] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 21:48:51] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 21:48:51] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 21:49:41] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 21:49:42] "GET /api/case_list?query=&pagenum=1&pagesize=15 HTTP/1.1" 404 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR app.py:1891 Exception on /api/case_list [GET]
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 21:51:57] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 21:51:57] "GET /api/case_list?query=&pagenum=1&pagesize=15 HTTP/1.1" 500 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 21:56:56] "GET /api/index HTTP/1.1" 200 -
ERROR app.py:1891 Exception on /api/case_list [GET]
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 21:56:56] "GET /api/case_list?query=&pagenum=1&pagesize=15 HTTP/1.1" 500 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 21:58:08] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 21:58:08] "GET /api/case_list?query=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 21:58:58] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 21:58:58] "GET /api/case_list?query=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 22:00:22] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 22:06:46] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 22:06:46] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 22:57:24] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 22:58:34] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 22:58:34] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 22:58:56] "GET /api/index HTTP/1.1" 200 -
ERROR case_api.py:43 'list' object has no attribute 'paginate'
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 22:58:57] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:01:20] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:01:21] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:06:52] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:06:53] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:06:53] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:09:43] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:09:45] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:09:45] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:10:23] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:10:23] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:12:23] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:12:23] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:13:31] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:13:31] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:14:27] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:14:27] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:14:27] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:14:27] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:14:39] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:14:43] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:14:43] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:18:59] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:19:04] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:19:04] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:25:16] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:27:18] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:27:18] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:32:25] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:32:25] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:57:55] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:57:55] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:57:59] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:57:59] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:58:15] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [13/Dec/2019 23:58:16] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 09:41:40] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 09:41:40] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 09:43:27] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 09:43:27] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 09:43:33] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 09:43:33] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 09:48:05] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 09:48:05] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 09:48:47] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 09:48:47] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:05:33] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:05:41] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:05:42] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:05:45] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:05:45] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:05:47] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:05:47] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:05:53] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:18:47] "GET /api/user HTTP/1.1" 404 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:19:23] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:19:23] "GET /api/user HTTP/1.1" 404 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:19:43] "GET /api/index HTTP/1.1" 200 -
ERROR app.py:1891 Exception on /api/user [GET]
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyProj\haizol_autoteset\utils\commons.py", line 38, in wrapper
    return view_func(*args, **kwargs)
  File "D:\PyProj\haizol_autoteset\managetest\api_list\user_api.py", line 117, in user
    return jsonify(code=200, message="请求成功", data=users)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Program Files\Python36\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Program Files\Python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'User' is not JSON serializable
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:19:43] "GET /api/user HTTP/1.1" 500 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:19:56] "GET /api/index HTTP/1.1" 200 -
ERROR app.py:1891 Exception on /api/user [GET]
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyProj\haizol_autoteset\utils\commons.py", line 38, in wrapper
    return view_func(*args, **kwargs)
  File "D:\PyProj\haizol_autoteset\managetest\api_list\user_api.py", line 117, in user
    return jsonify(code=200, message="请求成功", data=users)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Program Files\Python36\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Program Files\Python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'User' is not JSON serializable
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:19:56] "GET /api/user HTTP/1.1" 500 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:21:08] "GET /api/index HTTP/1.1" 200 -
ERROR app.py:1891 Exception on /api/user [GET]
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyProj\haizol_autoteset\utils\commons.py", line 38, in wrapper
    return view_func(*args, **kwargs)
  File "D:\PyProj\haizol_autoteset\managetest\api_list\user_api.py", line 118, in user
    return jsonify(code=200, message="请求成功", data=users)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\json\__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "C:\Program Files\Python36\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\Python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\Python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "C:\Program Files\Python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'User' is not JSON serializable
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:21:09] "GET /api/user HTTP/1.1" 500 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:24:33] "GET /api/index HTTP/1.1" 200 -
ERROR app.py:1891 Exception on /api/user [GET]
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyProj\haizol_autoteset\utils\commons.py", line 38, in wrapper
    return view_func(*args, **kwargs)
  File "D:\PyProj\haizol_autoteset\managetest\api_list\user_api.py", line 119, in user
    user_li.append(user.to_dict())
AttributeError: 'function' object has no attribute 'to_dict'
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:24:33] "GET /api/user HTTP/1.1" 500 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:25:46] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:25:46] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:28:10] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:28:10] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:30:27] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:30:27] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:35:03] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:36:02] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:36:02] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:36:33] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:36:35] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:36:35] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:36:49] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:36:49] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:38:43] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:38:43] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:38:48] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:38:52] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:38:52] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:41:06] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:41:09] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:41:09] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:42:08] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:42:08] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:43:14] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:43:14] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:49:26] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:49:26] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:49:26] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:50:08] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:50:08] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:50:17] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:50:17] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:54:59] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:55:46] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:55:46] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 10:57:42] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:02:17] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:02:17] "GET /api/case_list?keyword=&pagenum=1&pagesize=15 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:11:16] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:13:51] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:13:57] "GET /api/case_list?keyword=&pagenum=1&pagesize=20 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:14:03] "GET /api/case_list?keyword=&pagenum=1&pagesize=40 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:15:12] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:15:16] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:15:16] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:15:19] "GET /api/case_list?keyword=&pagenum=1&pagesize=2 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:15:27] "GET /api/case_list?keyword=&pagenum=1&pagesize=1 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:15:30] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:15:56] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:15:58] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:15:58] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:16:00] "GET /api/case_list?keyword=&pagenum=2&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:16:02] "GET /api/case_list?keyword=&pagenum=3&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:16:03] "GET /api/case_list?keyword=&pagenum=139&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:16:10] "GET /api/case_list?keyword=&pagenum=100&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:16:14] "GET /api/case_list?keyword=&pagenum=98&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:16:20] "GET /api/case_list?keyword=&pagenum=96&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:16:22] "GET /api/case_list?keyword=&pagenum=96&pagesize=40 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:16:22] "GET /api/case_list?keyword=&pagenum=35&pagesize=40 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:16:26] "GET /api/case_list?keyword=&pagenum=30&pagesize=40 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:16:39] "GET /api/case_list?keyword=&pagenum=1&pagesize=40 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:16:42] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:16:46] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:16:46] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:18:28] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:18:28] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:18:46] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:18:46] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:19:10] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:19:51] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:19:53] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:19:53] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:24:24] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:26:07] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [14/Dec/2019 11:26:07] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:24:09] "OPTIONS /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:24:10] "POST /api/login HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:24:10] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:24:14] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:24:22] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:24:53] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:24:53] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:25:31] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:25:37] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:25:37] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:26:26] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:26:32] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:26:32] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:26:35] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:26:35] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:27:04] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:27:07] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:27:07] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:28:00] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:30:47] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:30:47] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:30:51] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:30:51] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:30:56] "OPTIONS /api/update_status HTTP/1.1" 200 -
ERROR app.py:1891 Exception on /api/update_status [PUT]
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyProj\haizol_autoteset\utils\commons.py", line 38, in wrapper
    return view_func(*args, **kwargs)
  File "D:\PyProj\haizol_autoteset\managetest\api_list\user_api.py", line 128, in update_user_status
    user_id = req_dict('user_id')
TypeError: 'dict' object is not callable
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:30:56] "PUT /api/update_status HTTP/1.1" 500 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:32:09] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:32:09] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:32:20] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:32:20] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:32:28] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:32:34] "OPTIONS /api/update_status HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:32:34] "PUT /api/update_status HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:33:45] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:33:45] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:33:54] "OPTIONS /api/update_status HTTP/1.1" 200 -
ERROR app.py:1891 Exception on /api/update_status [PUT]
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyProj\haizol_autoteset\utils\commons.py", line 38, in wrapper
    return view_func(*args, **kwargs)
  File "D:\PyProj\haizol_autoteset\managetest\api_list\user_api.py", line 132, in update_user_status
    user = User.query.filter_by(id=user_id).frist()
AttributeError: 'BaseQuery' object has no attribute 'frist'
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:33:54] "PUT /api/update_status HTTP/1.1" 500 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:34:47] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:34:47] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:34:51] "OPTIONS /api/update_status HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:34:51] "PUT /api/update_status HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:35:01] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:35:01] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:43:47] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:43:47] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:45:41] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:45:41] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:45:44] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:45:44] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:45:53] "OPTIONS /api/update_status HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:45:53] "PUT /api/update_status HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:46:02] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:46:02] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:46:12] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:46:12] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:46:42] "OPTIONS /api/update_status HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:46:42] "PUT /api/update_status HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:47:20] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:47:25] "OPTIONS /api/update_status HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:47:25] "PUT /api/update_status HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:47:50] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:47:54] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:47:59] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:47:59] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:48:09] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:50:38] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:50:38] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:50:56] "GET /api/case_list?keyword=test_es_&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:51:03] "GET /api/case_list?keyword=test_es_&pagenum=2&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:51:05] "GET /api/case_list?keyword=test_es_&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:51:23] "GET /api/case_list?keyword=公司名&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:51:29] "GET /api/case_list?keyword=公司名&pagenum=2&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:51:30] "GET /api/case_list?keyword=公司名&pagenum=3&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:51:32] "GET /api/case_list?keyword=公司名&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:51:43] "GET /api/case_list?keyword=test_manage&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:51:48] "GET /api/case_list?keyword=test_manage&pagenum=2&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:51:50] "GET /api/case_list?keyword=test_manage&pagenum=3&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:51:51] "GET /api/case_list?keyword=test_manage&pagenum=4&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:51:51] "GET /api/case_list?keyword=test_manage&pagenum=5&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:51:52] "GET /api/case_list?keyword=test_manage&pagenum=6&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:52:49] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:52:49] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:52:54] "GET /api/case_list?keyword=jslfjoew&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:52:59] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:54:53] "GET /api/case_list?keyword=test_es_am&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 11:54:57] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 12:51:46] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 12:51:46] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:01:46] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:01:46] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:06:10] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:06:19] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:06:19] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:06:41] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:06:41] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:07:18] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:07:18] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:13:36] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:16:08] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:18:37] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:18:37] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:19:02] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:19:02] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:20:46] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:20:46] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:24:56] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:27:06] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:27:08] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:27:08] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:59:27] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 13:59:27] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:25:54] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:30:01] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:30:01] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:31:07] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:31:07] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:33:03] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:33:03] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:34:05] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:34:09] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:34:09] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:34:28] "OPTIONS /api/saveCase HTTP/1.1" 200 -
ERROR case_api.py:77 Class 'flask_sqlalchemy.model.DefaultMeta' is not mapped; was a class (managetest.models.TestCase) supplied where an instance was required?
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:34:28] "POST /api/saveCase HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:38:36] "OPTIONS /api/saveCase HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:38:36] "POST /api/saveCase HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:38:36] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:46:58] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:47:16] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:47:19] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:47:19] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:52:26] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:52:28] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:52:28] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:54:28] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:54:30] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:54:30] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:56:03] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:56:12] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 14:56:12] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:10:12] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:10:19] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:10:19] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
ERROR case_api.py:100 int() argument must be a string, a bytes-like object or a number, not 'NoneType'
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:10:22] "GET /api/get_case_by_id HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:15:27] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:15:36] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:15:36] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
ERROR case_api.py:106 Object of type 'method' is not JSON serializable
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:15:41] "GET /api/get_case_by_id?id=1386 HTTP/1.1" 200 -
ERROR case_api.py:106 Object of type 'method' is not JSON serializable
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:15:49] "GET /api/get_case_by_id?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR case_api.py:106 Object of type 'method' is not JSON serializable
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:18:14] "GET /api/get_case_by_id?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:19:00] "GET /api/get_case_by_id?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:19:27] "GET /api/get_case_by_id?id=1385 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:19:30] "GET /api/get_case_by_id?id=1384 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:19:33] "GET /api/get_case_by_id?id=1383 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:19:36] "GET /api/get_case_by_id?id=1382 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:25:39] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:25:39] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:25:42] "GET /api/get_case_by_id?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:27:52] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:27:56] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:27:56] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:28:40] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:28:42] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:28:42] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:28:44] "GET /api/get_case_by_id?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:28:51] "OPTIONS /api/saveCase HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:28:51] "POST /api/saveCase HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:29:23] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:29:29] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:29:29] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:29:31] "GET /api/get_case_by_id?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:29:37] "OPTIONS /api/saveCase HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:29:37] "POST /api/saveCase HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:29:37] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:29:41] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:29:41] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:32:47] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:32:47] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:35:10] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:35:10] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:35:14] "GET /api/get_case_by_id?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:35:27] "OPTIONS /api/saveCase HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:35:27] "POST /api/saveCase HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:35:27] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:37:11] "GET /api/get_case_by_id?id=1385 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:37:14] "GET /api/get_case_by_id?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:37:52] "GET /api/get_case_by_id?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:37:55] "GET /api/get_case_by_id?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:40:28] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:40:32] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:40:32] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:40:43] "GET /api/get_case_by_id?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:40:51] "GET /api/get_case_by_id?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:40:54] "GET /api/get_case_by_id?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:41:03] "GET /api/get_case_by_id?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:41:17] "GET /api/get_case_by_id?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:41:28] "OPTIONS /api/saveCase HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:41:28] "POST /api/saveCase HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 15:41:28] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:02:05] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:02:05] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:02:16] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:02:16] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:02:41] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:02:41] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:02:42] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:02:42] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:07:02] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:07:05] "OPTIONS /api/delete_case?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:07:05] "DELETE /api/delete_case?id=1386 HTTP/1.1" 405 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:07:11] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:07:11] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:07:19] "OPTIONS /api/delete_case?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:07:19] "DELETE /api/delete_case?id=1386 HTTP/1.1" 405 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:08:12] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:08:13] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:08:15] "OPTIONS /api/delete_case?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:08:15] "DELETE /api/delete_case?id=1386 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:08:15] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:10:15] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:10:27] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:10:27] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:15:06] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:15:15] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:15:17] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:34:39] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:34:39] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:34:46] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:34:49] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:34:51] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:34:52] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:34:52] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:35:01] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:35:04] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:37:28] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:37:30] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:37:36] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:39:36] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:39:38] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:39:41] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:39:43] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:39:43] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:40:02] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:40:02] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:40:45] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:40:45] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:40:48] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:40:48] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:40:51] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:40:54] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:40:54] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:40:57] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:40:58] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:41:03] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:41:06] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:41:06] "GET /api/user HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:41:27] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:47:03] "GET /api/case_list?keyword=&pagenum=1&pagesize=10 HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:48:29] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:49:22] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:50:03] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 16:52:06] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 18:44:58] "POST /api/task_list HTTP/1.1" 405 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 18:45:50] "GET /api/task_list HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 19:23:35] "GET /api/task_list HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR app.py:1891 Exception on /api/task_list [GET]
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyProj\haizol_autoteset\managetest\api_list\task_api.py", line 17, in task_list
    print(i.to_basic_dict())
  File "D:\PyProj\haizol_autoteset\managetest\models.py", line 106, in to_basic_dict
    report = self.reports.order_by(desc('id')).first()
AttributeError: 'InstrumentedList' object has no attribute 'order_by'
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 19:24:14] "GET /api/task_list HTTP/1.1" 500 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 19:30:58] "GET /api/task_list HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR app.py:1891 Exception on /api/task_list [GET]
Traceback (most recent call last):
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\PyProj\haizol_autoteset\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyProj\haizol_autoteset\managetest\api_list\task_api.py", line 18, in task_list
    task_li.append(i.to_basic_dict())
  File "D:\PyProj\haizol_autoteset\managetest\models.py", line 111, in to_basic_dict
    "report": self.reports[-1].name
IndexError: list index out of range
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 19:36:08] "GET /api/task_list HTTP/1.1" 500 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 19:37:28] "GET /api/task_list HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 19:53:42] "GET /api/task_list HTTP/1.1" 200 -
INFO _internal.py:122  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 19:54:00] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 19:54:00] "GET /api/task_list HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 19:56:27] "GET /api/task_list HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 21:21:00] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 21:21:00] "GET /api/task_list HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 22:34:59] "GET /api/index HTTP/1.1" 200 -
INFO _internal.py:122 127.0.0.1 - - [15/Dec/2019 22:34:59] "GET /api/task_list HTTP/1.1" 200 -
